callbacks:
  patience: 100
  tol: 0
data:
  baseMVA: 100
  learn_mask: false
  mask_dim: 6
  mask_ratio: 0.5
  mask_type: rnd
  mask_value: -1.0
  networks:
  # - Texas2k_case1_2016summerpeak
  - case24_ieee_rts
  # - case118_ieee
  # - case300_ieee
  - case89_pegase
  # - case240_pserc
  normalization: baseMVAnorm
  scenarios:
  # - 5000
  - 5000
  - 5000
  # - 30000
  # - 50000
  # - 50000
  test_ratio: 0.1
  val_ratio: 0.1
  workers: 4
model:
  attention_head: 8
  dropout: 0.1
  edge_dim: 2
  hidden_size: 123
  input_dim: 9
  num_layers: 10
  output_dim: 6
  pe_dim: 20
  type: GRIT  
  act: relu
  encoder:
    node_encoder: True
    edge_encoder: True
    node_encoder_name: TODO
    node_encoder_bn: True
  gt:
    layer_type: GritTransformer
    dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
    layer_norm: False
    batch_norm: True
    update_e: True
    attn_dropout: 0.2
    attn:
      clamp: 5.
      act: 'relu'
      full_attn: True
      edge_enhance: True
      O_e: True
      norm_e: True
      signed_sqrt: True
  posenc_RRWP:
    enable: True
    ksteps: 21
    add_identity: True
    add_node_attr: False
    add_inverse: False
optimizer:
  beta1: 0.9
  beta2: 0.999
  learning_rate: 0.0001
  lr_decay: 0.7
  lr_patience: 10
seed: 0
training:
  batch_size: 8
  epochs: 500
  loss_weights:
  - 0.01
  - 0.99
  losses:
  - MaskedMSE
  - PBE
  accelerator: auto
  devices: auto
  strategy: auto
